name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Create EXE installer
        run: |
          jpackage --name Lab2JavaFX `
                   --input target/ `
                   --main-jar lab2JAVA-1.0-SNAPSHOT.jar `
                   --main-class your.main.Class `
                   --type exe `
                   --win-shortcut `
                   --win-menu `
                   --vendor "YourName"

      - name: Upload EXE  artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: Lab2JavaFX.exe
