name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      JAVA_HOME: C:\Program Files\Java\jdk-21
      PATH_TO_FX: ${{ github.workspace }}\javafx-sdk-21.0.2\lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JavaFX SDK
        run: |
          Invoke-WebRequest -Uri "https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_windows-x64_bin-sdk.zip" -OutFile "javafx-sdk.zip"
          Expand-Archive -Path "javafx-sdk.zip" -DestinationPath .
          Rename-Item -Path "javafx-sdk-21.0.2" -NewName "javafx-sdk"

      - name: Build with Maven
        run: mvn clean package

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Create EXE installer
        run: |
          jpackage --type exe `
                   --name Lab2JavaFX `
                   --input target `
                   --main-jar lab2JAVA-1.0-SNAPSHOT.jar `
                   --main-class com.example.lab2java.HelloApplication `
                   --module-path $env:PATH_TO_FX `
                   --add-modules javafx.controls,javafx.fxml `
                   --win-shortcut `
                   --win-menu `
                   --vendor "YourName" `
                   --icon src/main/resources/icon.ico `
                   --dest release

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lab2JavaFX-Installer
          path: |
            release/Lab2JavaFX.exe
            release/Lab
